/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppDownloaderRouteImport } from './routes/_app/downloader'
import { Route as AppCaptionsRouteImport } from './routes/_app/captions'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDownloaderRoute = AppDownloaderRouteImport.update({
  id: '/downloader',
  path: '/downloader',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCaptionsRoute = AppCaptionsRouteImport.update({
  id: '/captions',
  path: '/captions',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteRoute
  '/captions': typeof AppCaptionsRoute
  '/downloader': typeof AppDownloaderRoute
}
export interface FileRoutesByTo {
  '/captions': typeof AppCaptionsRoute
  '/downloader': typeof AppDownloaderRoute
  '/': typeof AppRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/captions': typeof AppCaptionsRoute
  '/_app/downloader': typeof AppDownloaderRoute
  '/_app/': typeof AppRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/captions' | '/downloader'
  fileRoutesByTo: FileRoutesByTo
  to: '/captions' | '/downloader' | '/'
  id: '__root__' | '/_app' | '/_app/captions' | '/_app/downloader' | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/downloader': {
      id: '/_app/downloader'
      path: '/downloader'
      fullPath: '/downloader'
      preLoaderRoute: typeof AppDownloaderRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/captions': {
      id: '/_app/captions'
      path: '/captions'
      fullPath: '/captions'
      preLoaderRoute: typeof AppCaptionsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppCaptionsRoute: typeof AppCaptionsRoute
  AppDownloaderRoute: typeof AppDownloaderRoute
  AppRouteRoute: typeof AppRouteRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppCaptionsRoute: AppCaptionsRoute,
  AppDownloaderRoute: AppDownloaderRoute,
  AppRouteRoute: AppRouteRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
